### ISSUE TITLE
[feature request] forward osc without parsing, disable bundle scheduling and zeroconf browser

### ISSUE THREAD

**Issue by sambirk** [overtone/osc-clj#2]
Sam, following our brief twitter conversation last week here's some background on my goals:

Our laptop orchestra focuses on improvised performance practice and has deliberately chosen to avoid the development of a meta-instrument structure, opting rather to develop individual instruments and methodologies to promote interaction between performers.

In reaction to this evolving method, I'm developing a command line tool to be used along side a precise time protocol daemon that will act as an osc router with standardised name space. Allowing performers the ability, if so desired, to access meta-data and sync/merge into the performance without radically changing current practices.

Command line utility synopsis:

Sever A advertises its availability through zeroconf and receives from peers, forwarding messages and bundles on to a localhost port for use in the target software.

Server B is another forwarding server, messages and bundles received from target software should be forwarded on to both server A for local use and to all zeroconf peers.

In both servers, forwarding the original bundle time stamp for scheduling at the end of network traversal instead of locally scheduling is required (eliminating jitter at the cost of a small amount of latency) Data will be scheduled at just over half the round trip delay of the network into the future to ensure no bundles arrive late.

Adding fixed time tag offsets for differing audio interfaces and interfacing with software without osc scheduling also needs my thought.

In addition, linking osc name spacing to zeroconf peers could reduce overall network traffic.

Hope that makes sense, even though it probably breaks all osc specs.

**Comment by samaaron** [comment]
Sounds very interesting. Looks like all you need is a way of creating an OSC server that _doesn't_ schedule its bundles to be executed at a later date.

I think you probably have the rest of the parts to the solution in plain osc-clj.

I'll look into coding a solution for you.

**Comment by sambirk** [comment]
samaaron,

I've had a bit of a crack at this today with my free time before New Year.

Through experimentation, I've come to the conclusion that the latency of localhost OSC messages isn't audibly noticable, being below a couple of ms at boths ends of the flow. This means that creating an OSC server that doesn't schedule bundles isn't _stricly_ necessary for my needs.

So I've opted to treat internal communication as negliable in terms of cross system scheduling. Accepting non bundles internally then forwarding both to peers and locally at a fixed time-tag offset just high enough for all peers to receive and schedule (15ms seems a good balance), resulting in auibly equal execution times. Neat.

I have had an issue sending OSC via a client bound to a multicast IP though (replaced in code block below as just localhost) and the search for a relaible zeroconf browser for Clojure continues which would be preferable, negating the need for multicasting.

Season's Greetings.

```
(use 'overtone.osc)

(def NAME "samBiotic")
(def OFFSET 15)

(def FORWARDING-PORT 9001)
(def LOCAL-PORT 9002)
(def MULTICAST-PORT 10000)
(def MULTICAST-IP "localhost") ;;FIXME

(def forwarding-server (osc-server FORWARDING-PORT))
(def local-client (osc-client "localhost" LOCAL-PORT))

(def multicast-server (osc-server MULTICAST-PORT NAME))
(zero-conf-on)
(def multicast-client (osc-client MULTICAST-IP MULTICAST-PORT))

;(osc-listen forwarding-server (fn [msg] (println "forwarder: " msg)) :debug)
;(osc-listen multicast-server  (fn [msg] (println "multicast: " msg)) :debug)

(osc-listen forwarding-server (fn [msg] (in-osc-bundle multicast-client (+ (osc-now) OFFSET) (apply osc-send multicast-client (get msg :path) (get msg :args)))) :forwarder)
(osc-listen multicast-server  (fn [msg] (apply osc-send local-client (get msg :path) (get msg :args))) :forwarder)

;; example target application
(def target-server (osc-server LOCAL-PORT))
(osc-listen target-server (fn [msg] (println "target: " msg)) :debug)

(def target-client (osc-client "localhost" FORWARDING-PORT))
(osc-send target-client "/test" (rand 1000) (rand 1))

;; close osc servers and clients
(osc-rm-all-listeners forwarding-server)
(osc-rm-all-listeners multicast-server)
(osc-close forwarding-server)
(osc-close multicast-server)
(osc-close multicast-client)

;; close example target application server and client
(osc-rm-all-listeners target-server)
(osc-close target-server)
(osc-close target-client)
```

**Comment by sambirk** [comment]
Started a new repo to track this project https://github.com/samBiotic/zosc
